#+title: README

* Overview

This project uses [[https://orgmode.org/][org-mode]] to structure all documents, including the index page
and sub-pages such as blog posts.

* Configuration

If you want to replicate this project structure, you'll need to customize your
=.emacs= file appropriately, or load a custom =.el= file.

If you're within emacs while changing =.emacs=, you'll need to reload the
configuration with =M-x load-file= and hit enter to reload the current file
(=.emacs=).

See the [[./elisp/publish.el][publish.el]] file for this repository's 
configuration.

* Building

When ready to publish, open any of the =.org= files in the project and execute
=M-x org-publish-current-project=.

If you want to force emacs to re-publish all files, including files without
changes, execute =C-u M-x org-publish-current-project=.

The resulting files will be published to the =public/= directory within the 
repository, which is ignored via the =.gitignore= file. If you wish to publish 
the files remotely, you can change the =:publishing-directory= variable in 
=publish.el= or do a sync step outside of emacs:

#+begin_src sh
scp -r public/* ubuntu:/var/www/cleberg.net/
#+end_src
