#+date: <2019-12-03>
#+title: The Ansoff Matrix
#+description: 
#+slug: the-ansoff-matrix

* Overview

As the world of business evolves, managers must approach business
planning and strategy with a contemporary mindset. According to Dess,
McNamara, Eisner, and Lee, managers must be willing to adapt to the
modern business environment by going beyond "'incremental management',
whereby they view their job as making a series of small, minor changes
to improve the efficiency of the firm's operations"(2019).

One reason that strategic management is crucial is because most
businesses that fail in the United States each year fail due to a lack
of strategic focus or direction(2019). The rate of failure for
businesses with poor strategies shows that strategic planning and
management are crucial to a business's strength and longevity, injecting
the critical factors of growth and direction into a company's business
plan.

One of the most significant strategic planning and management frameworks
that companies can use is the
[[https://en.wikipedia.org/wiki/Ansoff_matrix][Ansoff Matrix]]. While
this framework has unique purposes and use-cases, it can effectively
help an organization grow and compete. Specifically, the Ansoff matrix
is one of the most effective frameworks for companies who want to focus
on increasing sales revenue or profitability(2019).

This framework uses a two-by-two figure to show the four strategic
options for companies to use in this framework: market penetration,
market development, product development, and diversification (see
*Figure 1*). The x-axis of the matrix focuses on the firm's markets and
also determines if the firm is looking to enter new markets or innovate
in its current markets. The y-axis of the matrix focuses on the firm's
products and determines if the firm wants to pursue strategies around
their existing products or explore new products.

* Strategic Options

** Market Penetration

The most straightforward strategy in the Ansoff matrix is to focus on
existing products in existing markets, also known as market
penetration(2019). Companies such as Coca-Cola have used market
penetration successfully by investing a lot of money to get further
value out of their current markets. Coca-Cola does this by introducing
new features such as Christmas-themed bottles, personal names on the
bottles, and other marketing schemes.

** Market Development

Market development extends existing products into new markets in an
attempt to increase the number of buyers. One interesting way that
Coca-Cola used this strategy comes from the stigma that Diet Coke is a
woman's drink(2019). Coca-Cola introduced Coca-Cola Zero, which
contained the same nutritional content as Diet Coke, but was packaged in
a dark black can to appear more "manly"(2019).

** Product Development

Product development uses existing markets to introduce new products so
that the firm can better meet customer needs(2019). The extreme end of
diversification is home to companies such as Johnson & Johnson, a
healthcare company that has developed a business portfolio of more than
60,000 different products(2019). Johnson & Johnson's dedication to
continuous diversification has led them to a balance sheet rating of
"AAA", industry recognition for diversification, and increases in their
investor dividends for 57 consecutive years(2019).

** Related Diversification

Diversification, the final strategy of the Ansoff Matrix, is more
difficult than the others since it involves exploring both new markets
and new products. Related diversification is a diversification strategy
that closely relates to the firm's core business. Coca-Cola's best
example of related diversification is its acquisition of Glaceau and
Vitamin Water, which expanded their drinking lines of business(2019).

** Unrelated Diversification

Unrelated diversification is a diversification strategy that does not
really relate to the firm's core business but still diversifies their
business portfolio. A good example of this would be a coffee company who
has decided to enter the market for bicycle sales. The main purpose of
this strategy is to an extremely diverse company that will not go
bankrupt if one market goes through difficult times. However, this
requires a lot of independent skills and heavy investments since the
company most likely cannot easily transfer knowledge between the markets
they compete in.

* Requirements for Success

To use the Ansoff Matrix framework, managers need to formulate corporate
goals and objectives. Without goals and direction, management frameworks
do not present much practical utility. Further, the Ansoff Matrix
requires the managers involved to make tactical decisions and create a
path for the company to take toward their goals. Lastly, both the Ansoff
Matrix needs to consider both internal and external perspectives
throughout the strategy formulation process.

One interesting probability is that companies will be using multiple
strategic planning and management frameworks at the same time. While
this may sound like it could crowd the management process, there are
numerous reasons to do so. For example, the Ansoff Matrix and the
Balanced Scorecard are relatively popular, and they cover entirely
different parts of a company's strategy. Using the results from the
Balanced Scorecard could inform a company of the potential product and
market demands, such as from customer or supplier survey results, to
help the company determine which Ansoff Matrix strategy to pursue.
However, a combined approach at this level would require mature
frameworks and focused managers who are able to strategize at a high
level.

Lastly, it should be noted that the author of the Ansoff matrix, Igor
Ansoff, often used the term
[[https://en.wikipedia.org/wiki/Analysis_paralysis][paralysis by
analysis]] to explain the mistake of companies who overuse analysis and
spend too much time planning. Companies need to understand the utility
of a strategic management framework while ensuring that the company is
poised to execute as efficiently as they have planned.
