#+date: <2021-01-01>
#+title: SEUM: Spreedrunners from Hell
#+description: 
#+slug: seum

* Game Description

[[https://store.steampowered.com/app/457210/SEUM_Speedrunners_from_Hell/][SEUM:
Speedrunners from Hell]] is an incredibly fast-paced mashup of a puzzle
game and a free-running game. Created by [[https://pinestudio.co][Pine
Studio]] in early 2016 and first released as a
[[https://gamejolt.com/games/seum-speedrunners-from-hell-demo/154868][demo
on GameJolt]], this game was successfully green-lit on Steam and has
amassed a cult following on multiple consoles.

Here's the game description straight from the developers:

#+begin_quote
Like a bastard child of Quake 3 and Super Meat Boy, SEUM: Speedrunners
from Hell is truly hardcore and focuses on speed and fast reaction.
#+end_quote

* Story

SEUM does a great job setting the stage when you open the game for the
first time, playing an animated video in the form of comic book images.
You see Marty, the protagonist, sitting around drinking his beer as
Satan busts down the door, cuts his hand off, and steals all his beer
and bacon. As Satan is leaving, Marty whips a vinyl record across the
room and cuts off one of Satan's hands. This hand is what allows you to
use all the powers in the game.

* Gameplay

To accomplish each level, you will need to get to the final blue portal
under a certain time limit. You can beat a level by getting to the
portal before the time meter runs out or "Dominate" a level by beating
it within a shorter time limit (noted by a bright red/orange color in
the time meter).

The portal is usually set behind locked gates, protected by dangerous
defenses, or in hard-to-reach places. To reach the portal, you'll need
to go through any existing orange portals, light all yellow beacons,
avoid things like fireballs and blades, or use any satanic power orbs
lying around. These special abilities include:

- Gravity
- Teleport
- Rewind
- Spawn platform
- Roar (DLC)
- Rocket (DLC)
- Shadow world (DLC)

For the main storyline, there are nine floors to beat. Each floor
contains nine regular levels, one boss level, and one bonus level;
although you don't technically need to beat all levels to advance to the
next floor. # In-Game Screenshots

The main menu gives you plenty of options for tuning your system,
playing main levels, playing the DLC, or exploring the other game modes.

Once you enter a level, you can look around and strategize before
starting. Clicking any button will start the menu, and you'll have to
restart if you die. One of the great things about SEUM is that it has
great keyboard shortcuts. You can quickly smash =R= to restart the level
or =M= to return to the level menu.

Once you're able to win a level, you'll see the high scores and can
watch replays of the best scores.

Each regular level also contains a beer in a disguised location that may
take some out-of-the-box thinking.
