#+title: Wiki
#+description: An informal wiki of sorts.

An informal wiki of sorts.

* Digital Garden

#+begin_quote
At times, wilderness is exactly what readers want: a rich collection of
resources and links. At times, rigid formality suits readers perfectly,
providing precisely the information they want, no more and no less.
Indeed, individual hypertexts and Web sites may contain sections that
tend toward each extreme.

#+end_quote

#+begin_quote
Often, however, designers should strive for the comfort, interest, and
habitability of parks and gardens: places that invite visitors to
remain, and that are designed to engage and delight them, to invite them
to linger, to explore, and to reflect.

#+end_quote

[[https://www.eastgate.com/garden/][Hypertext Garden]]

* Git

I want to get rid of all local modifications and go back to the working
tree of the most recent commit:

#+begin_src sh
git restore .
#+end_src

Revert a specified commit:

#+begin_src sh
git revert commit-id
#+end_src

Reset the repository to a specific commit in the git log:

#+begin_src sh
git reset --mixed commit-id
#+end_src

I need to commit and push changes to a remote that has been changed
since my most recent pull:

#+begin_src sh
git pull --rebase
#+end_src

* Hardware

** Laptops

*** macOS

| Category | Details         |
|----------+-----------------|
| Model    | Macbook Pro 16” |
| CPU      | Apple M2 Pro    |
| RAM      | 16GB            |
| Storage  | 512GB SSD       |

*** Linux

| Category | Details                                     |
|----------+---------------------------------------------|
| Model    | Lenovo ThinkPad E15 Gen 4, model 21ED0048US |
| CPU      | AMD Ryzen 5 5625U with Radeon Graphics      |
| RAM      | 16 GB                                       |
| Storage  | 256 GB SSD                                  |

** Servers

| Category           | Details                                |
|--------------------+----------------------------------------|
| Case               | Rosewill RSV-R4100U 4U                 |
| Motherboard        | NZXT B550                              |
| CPU                | AMD Ryzen 7 5700G with Radeon Graphics |
| RAM                | 64GB RAM (2x32GB)                      |
| Storage (On-board) | Western Digital 500GB M.2 NVME SSD     |
| Storage (HDD Bay)  | 48TB HDD                               |
| PSU                | Corsair RM850 PSU                      |

** Networking Equipment

- UDM-Pro
- USW-24-PoE
- USW-Lite-8-PoE
- U6-Pro
- U6-Extender
- USP-Plug
- UVC G4 Instant x 3
- UVC G4 Doorbell Pro
- UP Chime
- USW 24-Port Patch Panel
- USW Switch Lite 8 PoE

* Software

** Laptop

Alpine 3.18.2; no DE.

I currently run my Alpine laptop via the default login shell - no
desktop environment. From here, I use a mix of byobu and emacs to split
my screen into tabs and panes. All programs run through the shell and do
not use visual libraries such as X or Wayland.

I have Sway installed and configured, but only launch it when I must.

- brightnessctl
- byobu
- emacs
- [font-dejavu, font-noto, font-noto-cjk, font-noto-cjk-extra]
- glances
- gnupg
- irssi
- lynx
- nano
- neomutt
- newsboat
- ohmyzsh
- [pango, pango-tools]
- pipewire
- syncthing
- wireguard
- zola
- zsh

** Server

Ubuntu 22.04.1; no DE.

See my services page for a list of the publicly-available services
running on this server.

- certbot
- [docker, docker-compose]
- nginx
- zsh
