#+title: macOS
#+date: <2024-05-01>

Related:

- [[https://cleberg.net/wiki/hardware/][Hardware]]

My primary OS. Currently running macOS Sonoma 14. This wiki page
contains most of the apps I have used at one point or another across my
different Macbooks.

(=*=) = My favorites

** Configuration
:PROPERTIES:
:CUSTOM_ID: configuration
:END:
*** Disable System Services
:PROPERTIES:
:CUSTOM_ID: disable-system-services
:END:
- [[https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection][Disabling
  and Enabling System Integrity Protection]]
- Disable Gatekeeper: =sudo spctl --master-disable=

*** Dotfiles
:PROPERTIES:
:CUSTOM_ID: dotfiles
:END:
These are probably out of date, but they give a general idea of how I
configure my machine.

#+begin_src conf
# ~/.zshrc
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"
export EDITOR="/opt/homebrew/bin/emacs -nw"
ZSH_THEME="bureau"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
#+end_src

#+begin_src conf
# ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
#+end_src

#+begin_src conf
# ~/.config/skhd/skhdrc
cmd - return : /Applications/iTerm.app/Contents/MacOS/iTerm2
cmd + shift - return : /Applications/LibreWolf.app/Contents/MacOS/librewolf
#+end_src

#+begin_src conf
# ~/.config/yabai/yabairc
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  15             \
    bottom_padding               15             \
    left_padding                 15             \
    right_padding                15             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap
echo "yabai configuration loaded.."
#+end_src

** Software
:PROPERTIES:
:CUSTOM_ID: software
:END:
*** Browsers
:PROPERTIES:
:CUSTOM_ID: browsers
:END:
- [[https://librewolf.net/][Librewolf]] (=*=) - Custom version of
  Firefox, focused on privacy and security
  - [[https://bitwarden.com/][Bitwarden]] - An open source password
    manager
  - [[https://darkreader.org/][Dark Reader]] - Dark mode for all the
    websites
  - [[https://libredirect.github.io/][Libredirect]] - Automatic web
    redirections
  - [[https://strongboxsafe.com/][Strongbox]] - Keepass password manager
    for iOS & macOS
  - [[https://ublockorigin.com/][uBlock Origin]] - Free, open-source ad
    content blocker
- [[https://github.com/ungoogled-software/ungoogled-chromium][Ungoogled
  Chromium]] - Google Chromium, sans integration with Google
- [[https://www.gnu.org/software/emacs/manual/html_mono/eww.html][eww]] -
  Emacs Web Wowser, for TUI browsing

*** Command Line Tools
:PROPERTIES:
:CUSTOM_ID: command-line-tools
:END:
- [[https://github.com/mr-karan/doggo][doggo]] - Command-line DNS Client
  for Humans
- [[https://github.com/muesli/duf][duf]] - Disk Usage/Free Utility - a
  better 'df' alternative
- [[https://github.com/bootandy/dust][dust]] - A more intuitive version
  of du in rust
- [[https://github.com/eza-community/eza][eza]] - A modern alternative
  to ls
- [[https://github.com/Macchina-CLI/macchina][macchina]] - A system
  information frontend with an emphasis on performance.
- [[https://github.com/yt-dlp/yt-dlp][yt-dlp]] - A youtube-dl fork with
  additional features and fixes

*** Communications
:PROPERTIES:
:CUSTOM_ID: communications
:END:
- [[https://element.io/][Element]] (=*=) - Matrix's default GUI client
- [[https://github.com/tulir/gomuks][gomuks]] - A terminal based Matrix
  client
- [[https://www.thunderbird.net/][Thunderbird]] (=*=) - An open source
  email client by Mozilla
- [[https://signal.org/][Signal]] (=*=) - A simple, powerful, and secure
  messenger

*** Development
:PROPERTIES:
:CUSTOM_ID: development
:END:
- [[https://www.docker.com/products/docker-desktop/][Docker Desktop]] -
  Docker containers for your desktop
  - [[https://github.com/open-webui/open-webui][open-webui]] -
    User-friendly WebUI for LLMs
- [[https://iterm2.com/][iTerm2]] (=*=) - The best terminal for macOS,
  hands down
- [[https://podman-desktop.io/][Podman Desktop]] (=*=) - Open source
  tool for containers and Kubernetes
- [[https://developer.apple.com/xcode/][Xcode]] - Apple's IDE
- [[https://en.wikipedia.org/wiki/Z_shell][zsh]] (=*=) - My shell
  preference due to its plugin and theme community
  - [[https://github.com/zsh-users/zsh-autosuggestions][zsh-autosuggestions]]
    - Fish-like autosuggestions for zsh
  - [[https://github.com/zsh-users/zsh-syntax-highlighting][zsh-syntax-highlighting]]
    - Fish shell like syntax highlighting for Zsh

*** Editors
:PROPERTIES:
:CUSTOM_ID: editors
:END:
- [[https://github.com/doomemacs/doomemacs][Doom Emacs]] (=*=) - An
  Emacs framework, great for working in org-mode
- [[https://obsidian.md/][Obsidian]] - A nice Markdown-based editor
  based on a "vault" structure. Offers a paid sync solution and
  community extensions
- [[https://standardnotes.com/][Standard Notes]] - A simple text editor
  focused on privacy and security. Offers a paid sync solution and
  community extensions
- [[https://vscodium.com/][VSCodium]] - VS Code without proprietary
  blobs

*** Media
:PROPERTIES:
:CUSTOM_ID: media
:END:
- [[https://skylum.com/luminar][Luminar]] - Luminar offers top-notch
  photo editing features
- [[https://www.minecraft.net/][Minecraft]] - Block mining simulator
- [[https://netnewswire.com/][NetNewsWire]] - A free and open source RSS
  reader for Mac, iPhone, and iPad
- [[https://www.plex.tv/][Plex]] (=*=) - Desktop client for the Plex
  Media Server
- [[https://store.steampowered.com/][Steam]] - The top gaming
  marketplace for computers
- [[https://transmissionbt.com/][Transmission]] (=*=) - A Fast, Easy and
  Free Bittorrent Client
- [[https://www.videolan.org/vlc/][VLC]] - A free and open source
  cross-platform multimedia player

*** Package Management
:PROPERTIES:
:CUSTOM_ID: package-management
:END:
- [[https://brew.sh/][Homebrew]] (=*=) - The Missing Package Manager for
  macOS (or Linux)
- [[https://www.macports.org/][MacPorts]] - A system to compile,
  install, and manage open source software

*** Utilities
:PROPERTIES:
:CUSTOM_ID: utilities
:END:
- [[https://betterdisplay.pro/][BetterDisplay]] - Allows you to tweak a
  ton of features of built-in and external screens, such as scaling,
  configuration overrides, and color/brightness upscaling
- [[https://bitwarden.com/][Bitwarden]] - An open source password
  manager
- [[https://icemenubar.app/][Ice]] (=*=)- A powerful menu bar management
  tool
- [[https://obdev.at/products/littlesnitch/index.html][LittleSnitch]] -
  Shows all network connections on your Macbook, including system and
  privileged services
- [[https://obdev.at/products/microsnitch/index.html][MicroSnitch]] -
  Camera & microphone monitoring and alterting service
- [[https://mullvad.net/][Mullvad]] (=*=) - A private VPN service
- [[https://ollama.com/][Ollama]] - Run Llama 2, Code Llama, and other
  models locally on your machine
  - [[https://github.com/kghandour/Ollama-SwiftUI][Ollama Swift]] - User
    Interface made for Ollama.ai using Swift
- [[https://orbstack.dev/][OrbStack]] - A fast and convenient GUI to
  manage Docker contains and Linux VMs
- [[https://www.raycast.com/][Raycast]] - A collection of tools and
  shortcuts, an alternative to Spotlight
- [[https://github.com/koekeishiya/skhd][skhd]] (=*=) - Simple hotkey
  daemon for macOS
- [[https://strongboxsafe.com/][Strongbox]] - Keepass password manager
  for iOS & macOS
- [[https://syncthing.net/][Syncthing]] (=*=) - Continuous file
  synchronization
- [[https://www.bresink.com/osx/TinkerTool.html][TinkerTool]] - Unlock
  hidden configuration options for macOS
- [[https://github.com/koekeishiya/yabai][yabai]] (=*=) - Automatic
  window tiling
